// Scaffolding System for Ollama Parity with Claude
//
// This module implements techniques to make local LLMs perform
// at near-Claude levels through structured prompting and validation.

pub mod json_validator;
pub mod chain_of_thought;
pub mod examples;
pub mod decomposer;
pub mod verifier;
pub mod error_recovery;
pub mod router;
pub mod agent_loop;
pub mod context_manager;
pub mod tool_cache;
pub mod ollama_agent;
pub mod self_correction;
pub mod lean_agent;
pub mod persistence;
pub mod safe_executor;
pub mod guaranteed_success;
pub mod unified_agent;
pub mod intelligence_engine;
pub mod intelligence_v2;
pub mod session_state;
pub mod smart_edit;
pub mod workflows;
pub mod multi_edit;
pub mod todo_tracker;
pub mod command_palette;
pub mod pane_manager;
pub mod hybrid_router;
pub mod embedding_engine;
pub mod template_library;
pub mod micro_models;
pub mod orchestrator;
pub mod plan_mode;
pub mod background_tasks;
pub mod streaming;
pub mod hooks;
pub mod skills;
pub mod mcp;
pub mod speed_cache;
pub mod web_search;
pub mod config_files;
pub mod parallel_agents;
pub mod autocomplete;
pub mod hot_reload;
pub mod autonomy;
pub mod subagents;
pub mod intent_sanitizer;
pub mod task_executor;
pub mod privacy_logger;
pub mod external_ai;
pub mod test_harness;

// Re-export main types
pub use json_validator::{ToolCall, ToolCallValidator, ValidationError};
pub use chain_of_thought::{ReasonedResponse, ChainOfThoughtEnforcer};
pub use examples::{Example, ExampleLibrary};
pub use decomposer::{SubTask, TaskDecomposer};
pub use verifier::{VerificationResult, SelfVerifier};
pub use error_recovery::{RecoveryStrategy, ErrorRecovery};
pub use router::{ModelType, ModelRouter};
pub use agent_loop::{AgentLoop, AgentState, LoopConfig};
pub use context_manager::{ContextManager, ContextConfig};
pub use tool_cache::{ToolCache, CacheConfig, CachedResult};
pub use ollama_agent::{OllamaAgent, OllamaAgentConfig, AgentEvent, StreamingConfig};
pub use self_correction::{SelfCorrectionEngine, SelfCorrectionConfig, ValidationResult as CorrectionResult};
pub use lean_agent::{LeanState, TaskPhase, OutputParser, DefaultActions, build_atomic_prompt};
pub use persistence::{PersistentTask, TaskStatus, FileBackup, ProtectedFiles};
pub use safe_executor::{SafeExecutor, ExecutionResult, run_autonomous_task};
pub use guaranteed_success::{GuaranteedSuccess, AtomicAction, ParsedAction, GuaranteedPrompt, PhasePrompts};
pub use unified_agent::{UnifiedAgent, UnifiedConfig, AgentMode, UnifiedEvent};
pub use intelligence_engine::{IntelligenceEngine, TaskType, ParsedTask, KeywordClassifier, WorkflowEngine};
pub use intelligence_v2::{IntelligenceEngineV2, TaskType as TaskTypeV2, ExecutionResult as ExecutionResultV2, ProcessedRequest, ExtractedEntities};
pub use session_state::{SessionState, ProjectType, ProjectContext, HistoryEntry, session, save_session as save_session_state};
pub use smart_edit::{SmartEditor, EditResult, EditType, EditOperation};
pub use workflows::{Workflow, WorkflowStep, WorkflowParam, WorkflowStore, WorkflowRun, workflows, get_builtin_workflows};
pub use multi_edit::{MultiEditEngine, MultiEditTransaction, TransactionResult, TransactionBuilder, EditType as MultiEditType, multi_edit};
pub use todo_tracker::{TodoTracker, Todo, TodoStatus, TodoSession, TodoStats, todos};
pub use command_palette::{CommandPalette, PaletteItem, PaletteAction, ItemCategory, SearchResult, FuzzyMatcher, palette};
pub use pane_manager::{PaneManager, Pane, Tab, PaneLayout, LayoutNode, SplitDirection, PaneSize, panes};
pub use hybrid_router::{HybridRouter, RequestType as HybridRequestType, ProcessingPath, RoutingDecision, RoutingStats, router, stats as routing_stats, route_request};
pub use embedding_engine::{EmbeddingEngine, CodeChunk, ChunkType, EmbeddedChunk, SearchResult as EmbeddingSearchResult, embeddings};
pub use template_library::{TemplateLibrary, CodeTemplate, TemplateCategory, Placeholder, TemplateResult, templates};
pub use micro_models::{MicroModelManager, ModelId, ModelCapabilities, ModelInfo, TaskType as ModelTaskType, LoadedModel, ModelManagerConfig, PromptFormat, ModelManagerStats, manager as model_manager, select_for_task, record_task};
pub use orchestrator::{orchestrate, OrchestratorContext, OrchestratorResult, OrchestratorStats, get_orchestrator_stats, get_combined_stats, record_orchestration, InstantResult, SearchResult as OrchestratorSearchResult, GeneratedResult, ErrorResult, ToolCall as OrchestratorToolCall, ToolResult as OrchestratorToolResult, poll_browser_response, get_bridge_queue};
pub use plan_mode::{Plan, PlanStep, PlanStatus, StepStatus, ActionType, PlanGenerator, should_plan, create_plan, get_current_plan, approve_current_plan, reject_current_plan, is_plan_response, has_pending_plan, plan_store};
pub use background_tasks::{BackgroundTask, TaskType as BgTaskType, TaskStatus as BgTaskStatus, TaskProgress, TaskResult, TaskSummary, TaskHandle, task_manager, spawn_task, get_all_tasks, get_running_tasks, get_task, cancel_task, get_task_summary, format_task, format_running_tasks};
pub use streaming::{StreamChunk, StreamSender, StreamReceiver, SearchResultChunk, ProgressChunk, MetaChunk, create_stream, create_stream_with_delay, stream_shell_output, stream_file_content, stream_search_results, stream_template, stream_registry, create_buffered_stream, push_to_stream, drain_stream, close_stream};
pub use hooks::{Hook, HookTrigger, HookAction, HookConditions, HookContext, HookResult, HookManager, hooks, register_hook, unregister_hook, run_hooks, create_builtin_hooks, init_hooks};
pub use skills::{Skill, SkillCategory, SkillHandler, SkillInvocation, SkillResult, SkillManager, skills, parse_skill, execute_skill, list_skills, search_skills};
pub use mcp::{McpTool, McpToolResult, McpContent, McpManager, McpServer, McpConfig, mcp, add_mcp_server, connect_mcp_server, call_mcp_tool, list_mcp_tools, load_mcp_config, list_mcp_servers};
pub use speed_cache::{SpeedCache, CachedResponse, CacheStats, speed_cache, cache_get, cache_set, cache_tool_get, cache_tool_set, cache_stats};
pub use web_search::{WebSearchEngine, SearchResult as WebSearchResult, SearchResponse, FetchedPage, SearchEngine, WebSearchConfig, web_search, search as web_search_query, fetch as web_fetch};
pub use config_files::{ConfigParser, ProjectConfig, ConfigFile, ConfigFormat, ProjectRules, AgentSettings, CodingStyle, load_config, reload_config, get_instructions, get_rules, create_config};
pub use parallel_agents::{ParallelExecutor, ParallelTask, AgentResult as ParallelAgentResult, AgentStatus, ParallelExecutionResult, ParallelConfig, FileConflict, executor as parallel_executor, execute_parallel, create_task as create_parallel_task, cancel_all as cancel_all_agents};
pub use autocomplete::{AutoCompleteEngine, Suggestion, SuggestionKind, CompletionContext, AutoCompleteConfig, autocomplete, complete, add_history};
pub use hot_reload::{HotReloadIndexer, IndexEvent, IndexEventType, IndexStats, HotReloadConfig, hot_reload, watch as watch_directory, unwatch as unwatch_directory, start as start_watcher, stop as stop_watcher, reindex, stats as indexer_stats};
pub use autonomy::{AutonomyController, AutonomyLevel, AutonomyConfig, ToolPermission, ApprovalRequest, ApprovalResponse, RiskLevel, autonomy, requires_approval, dispatch_mode_on, dispatch_mode_off, is_dispatch_mode, set_level as set_autonomy_level, get_level as get_autonomy_level, approve};
pub use subagents::{SubagentManager, Subagent, AgentSpecialization, SubagentStatus, SubTask as SubagentTask, TaskContext, SubagentResult, DelegationPlan, PlanStatus as DelegationPlanStatus, SubagentConfig, subagents, create_plan_sync as create_delegation_plan, execute_plan_sync as execute_delegation_plan, get_plan as get_delegation_plan, cancel_plan as cancel_delegation_plan};
pub use external_ai::{AIConfig, ChatMessage, AIResponse, AIError, AIProvider, UnifiedAI, ClaudeClient, OpenAIClient, check_ai_status, call_claude, call_openai, call_ai, set_api_key};
pub use test_harness::{TestCase, TestResult, TestSummary, run_single_test, run_test_suite, run_smoke_test, get_default_test_suite, format_results_terminal, format_results_json, is_test_running, get_last_summary, run_and_store_tests};
